version: '3'

services:
  db:
    image: postgres
    container_name: sitebuilder
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5435:5435
    restart: always